files:
  include: '/assets/sass/**/*.scss'
rules:
  class-name-format: 0
  mixins-before-declarations: 0
  indentation:
    - size: space
  no-color-literals:
    - 1
    - allow-rgba: 1
  placeholder-in-extend: 0
